### Read in .csv files to begin removing/adding any model-specific columns

In [1]:
import pandas as pd
import numpy as np

In [2]:
flights = pd.read_csv('flights_.csv', index_col=0) # the latest flight data, with feature_engineered columns
#passengers = pd.read_csv('passengers_jan-dec_18-19.csv') # the latest passenger data

C:\Users\jsusn\anaconda3\envs\py36\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (26) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
flights.head()

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,...,origin_wind_speed,origin_visibility,origin_conditions,dest_wind_speed,dest_visibility,dest_conditions,holiday,year,month,scheduled_flight_hour_of_day
60659,2018-01-01,UA,UA,UA,745,UA,N848UA,745,12953,LGA,...,14.8,9.9,Clear,12.3,9.1,Partially cloudy,True,2018,1,14
23125,2018-01-01,UA,UA_CODESHARE,UA,3582,YX,N649RW,3582,11298,DFW,...,15.0,9.9,Partially cloudy,12.3,9.1,Partially cloudy,True,2018,1,20
3646,2018-01-01,UA,UA,UA,1591,UA,N87527,1591,11298,DFW,...,15.0,9.9,Partially cloudy,5.6,4.2,Clear,True,2018,1,5
73558,2018-01-01,WN,WN,WN,5500,WN,N8685B,5500,11292,DEN,...,12.3,9.1,Partially cloudy,14.6,9.9,Partially cloudy,True,2018,1,18
77601,2018-01-01,WN,WN,WN,415,WN,N8690A,415,12892,LAX,...,5.6,4.2,Clear,12.7,9.9,Clear,True,2018,1,12

### One-Hot encoding for:
- weather
- origin_city_name and dest_city_name
- day_of_week

In [4]:
flights.columns

Index(['fl_date', 'mkt_unique_carrier', 'branded_code_share', 'mkt_carrier',
       'mkt_carrier_fl_num', 'op_unique_carrier', 'tail_num',
       'op_carrier_fl_num', 'origin_airport_id', 'origin', 'origin_city_name',
       'dest_airport_id', 'dest', 'dest_city_name', 'crs_dep_time', 'dep_time',
       'dep_delay', 'taxi_out', 'wheels_off', 'wheels_on', 'taxi_in',
       'crs_arr_time', 'arr_time', 'arr_delay', 'cancelled',
       'cancellation_code', 'diverted', 'crs_elapsed_time',
       'actual_elapsed_time', 'air_time', 'distance', 'carrier_delay',
       'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay',
       'first_dep_time', 'total_add_gtime', 'longest_add_gtime',
       'day_of_the_week', 'origin_wind_speed', 'origin_visibility',
       'origin_conditions', 'dest_wind_speed', 'dest_visibility',
       'dest_conditions', 'holiday', 'year', 'month',
       'scheduled_flight_hour_of_day'],
      dtype='object')

In [5]:
dest_conditions = pd.get_dummies(flights['dest_conditions'], prefix='dest')
origin_conditions = pd.get_dummies(flights['origin_conditions'], prefix='origin')

origin_city_name = pd.get_dummies(flights['origin_city_name'], prefix='origin')
dest_city_name = pd.get_dummies(flights['dest_city_name'], prefix='dest')

day_of_week = pd.get_dummies(flights['day_of_the_week'])

In [6]:
df_flights = pd.concat([flights['year'], flights['month'], day_of_week, origin_city_name, origin_conditions, flights['origin_visibility'], flights['origin_wind_speed'], dest_city_name, dest_conditions, flights['dest_visibility'], flights['dest_wind_speed'], flights['origin_visibility'], flights['holiday'], flights['arr_delay']], axis=1)

In [7]:
df_flights

,year,month,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,origin_atlanta,...,"dest_Rain, Overcast","dest_Rain, Partially cloudy",dest_Snow,"dest_Snow, Overcast","dest_Snow, Partially cloudy",dest_visibility,dest_wind_speed,origin_visibility,holiday,arr_delay
60659,2018,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,9.1,12.3,9.9,True,-36.0
23125,2018,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,9.1,12.3,9.9,True,-21.0
3646,2018,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,4.2,5.6,9.9,True,-14.0
73558,2018,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,9.9,14.6,9.1,True,-23.0
77601,2018,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,9.9,12.7,4.2,True,-18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140619,2019,12,0,0,0,0,0,1,0,0,...,0,0,0,0,0,9.9,6.1,9.9,False,-15.0
106829,2019,12,0,0,0,0,0,1,0,0,...,0,0,0,0,0,8.7,15.3,7.9,False,37.0
106104,2019,12,0,0,0,0,0,1,0,0,...,0,0,0,0,0,9.9,13.2,9.6,False,-28.0
103182,2019,12,0,0,0,0,0,1,0,0,...,0,0,0,1,0,7.9,25.3,8.7,False,-8.0
170119,2019,12,0,0,0,0,0,1,0,0,...,0,0,0,1,0,7.9,25.3,9.3,False,-12.0